/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariomdi;

/**
 *
 * @author Sucely Alvarez
 */
public class NewMDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    private MANTENIMIENTO_MAESTROS ventanamaestros;
    private MANTENIMIENTO_ALUMNOS ventanaalumnos;
    public NewMDIApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menucatalogos = new javax.swing.JMenu();
        menualumnos = new javax.swing.JMenuItem();
        menumaestros = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        botonsalida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        desktopPane.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 600, 390);

        menucatalogos.setMnemonic('f');
        menucatalogos.setText("Catalogos");

        menualumnos.setMnemonic('o');
        menualumnos.setText("Mantenimiento Alumnos");
        menualumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menualumnosActionPerformed(evt);
            }
        });
        menucatalogos.add(menualumnos);

        menumaestros.setMnemonic('s');
        menumaestros.setText("Mantenimiento Maestros");
        menumaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumaestrosActionPerformed(evt);
            }
        });
        menumaestros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menumaestrosKeyPressed(evt);
            }
        });
        menucatalogos.add(menumaestros);

        menuBar.add(menucatalogos);

        editMenu.setMnemonic('e');
        editMenu.setText("Salida");

        botonsalida.setMnemonic('t');
        botonsalida.setText("Salir del Sistema");
        botonsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalidaActionPerformed(evt);
            }
        });
        editMenu.add(botonsalida);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalidaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonsalidaActionPerformed

    private void menumaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumaestrosActionPerformed
        // TODO add your handling code here:
        ventanamaestros=new MANTENIMIENTO_MAESTROS();
        jDesktopPane1.add(ventanamaestros);
        //ventanamaestros.setVisible(true);
    }//GEN-LAST:event_menumaestrosActionPerformed

    private void menumaestrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menumaestrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menumaestrosKeyPressed

    private void menualumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menualumnosActionPerformed
        // TODO add your handling code here:
        ventanaalumnos=new MANTENIMIENTO_ALUMNOS();
        jDesktopPane1.add(ventanaalumnos);
        //ventanaalumnos.setVisible(true);
    }//GEN-LAST:event_menualumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem botonsalida;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menualumnos;
    private javax.swing.JMenu menucatalogos;
    private javax.swing.JMenuItem menumaestros;
    // End of variables declaration//GEN-END:variables

}
